Fibo examples
DataFabricRus/ontology-fts pull request #27
Opened 2017-10-27 12:23 UTC by yuricus

2017-10-27 12:30 UTC, yuricus reviewed
Добавил вопросы про пример и онтологию.

2017-10-27 12:30 UTC, yuricus commented on fibo-ru/ontology.ttl
> +fibo-ru:VATIN rdf:type owl:Class ;
VAT = НДС (налог на добавленную стоимость), 
1) РФ плательщиками НДС являются только юр. лица, да и то не все. - в примере fibo-ru:VATIN используется для ИНН физ. лица
2) В РФ конечно при платеже НДС импользуется ИНН ЮЛ, но этот ИНН используется и для еще кучи целей.

Предлагаю переосмыслить 2) и в случае 1) использовать другой класс

2017-10-27 12:30 UTC, yuricus commented on fibo-ru/examples/le-datafabric_llc.ttl
> +                fibo-be-le-lp:LegalPerson,
А должна ли быть компания fibo-be-le-lp:LegalPerson?

2017-10-27 12:31 UTC, KMax commented on fibo-ru/examples/le-datafabric_llc.ttl
> +                fibo-be-le-lp:LegalPerson,
Да, согласно FIBO LegalEntity подкласс LegalPerson.

2017-10-27 12:33 UTC, KMax commented on fibo-ru/ontology.ttl
> +fibo-ru:VATIN rdf:type owl:Class ;
О да, предложения приветствуются. У меня нет четко понимания, как смоделировать ИНН для ЮЛ, ИП и ФЗ.

2017-10-29 22:47 UTC, KMax commented on fibo-ru/ontology.ttl
> +fibo-ru:VATIN rdf:type owl:Class ;
@yuricus Вспомнил, я основывался на статье в Википедии (https://en.wikipedia.org/wiki/VAT_identification_number), которая говорит, что ИНН в РФ это аналог VAT в других странах, поэтому использовал эту аббревиатуру.

2017-11-23 08:24 UTC, ehlyzov requested changes

2017-11-23 08:24 UTC, ehlyzov commented on fibo-ru/examples/ie-hlyzov.ttl
> +:Hlyzov-EO a fibo-be-le-lp:NaturalPerson ;
Предлагаю также создать экземпляр foaf:Person, чтобы можно было разобрать ФИО

2017-11-23 08:26 UTC, KMax commented on fibo-ru/examples/ie-hlyzov.ttl
> +:Hlyzov-EO a fibo-be-le-lp:NaturalPerson ;
В данных foaf:Person уже будет, так как он добавляется в ФТС. Нужно ли повторять этот трипл и в FIBO?

2017-12-14 06:52 UTC, KMax commented
@yuricus @ehlyzov @DramaticallyDecayed Давай смерджим, если нет возражений/предложений?

2017-12-14 10:57 UTC, DramaticallyDecayed reviewed
Изменения в части представления адресов

2017-12-14 10:57 UTC, DramaticallyDecayed commented on fibo-ru/examples/le-datafabric_llc.ttl
> +        fts:p98_located_at :Region-78 ;
 Мы же теперь через один `fts:p98_located_at ` связываемся?
Т.е. вместо `fts:p98_located_at :Region-78 ;` и `fts:p98_located_at :Street-1` имеем
`fts:p98_located_at :House-1 ;`

И далее определение отдельных элементов. Дом:

`:House-1 a fts:C117_House_Element ;`

Улица:
```
:Street-1 a fts:C100_Street_Element;
    fts:p19_kladr_code "780000000000684" ;
    fts:p25_element_type "улица" ; 
    fts:p6_name "Латышских стрелков";
    fts:p113_part_of :House-1 .
```
Регион:
```
:Region-1 a fts:C96_Region_Element;
    fts:p19_kladr_code "78" ;
    fts:p25_element_type "ГОРОД" ; 
    fts:p6_name "САНКТ-ПЕТЕРБУРГ";
    fts:p113_part_of :Street-1 .
```

2018-04-07 16:59 UTC, merged