Update FTS ontology
DataFabricRus/ontology-fts pull request #29
Opened 2017-11-28 12:17 UTC by DramaticallyDecayed

Going to resolve #28 
Change list:
1. Add `C117_House_Element`
2. Remove `p20_address_code`
3. Rename `p19_region_code` to `p19_kladr_code`

2017-11-28 14:48 UTC, ehlyzov requested changes
Пожалуйста перенеси вручную изменения, чтобы был нормальный diff

2017-12-07 09:30 UTC, KMax approved these changes
А мы не можем определить `rdfs:domain` для `p19_kladr_code`?

В остальном все ок. Спасибо!

2017-12-07 10:51 UTC, ehlyzov approved these changes

2017-12-14 06:55 UTC, KMax commented
@DramaticallyDecayed Давай мерджить и я закрываю #28.

2017-12-14 11:48 UTC, merged

2017-12-14 11:49 UTC, DramaticallyDecayed commented
Merged with update-ontology-28 to close #28